# Generated by Django 2.1.5 on 2019-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetail',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
